### PR TITLE
Proposal for a .svg synaptic icon

### PR DESCRIPTION
**Pull request by LLdaniel**
This is a first proposal  for a  `.svg` synaptic icon which addresses issue #28 . I am by far no designer so please feel free to give feedback and suggest changes and I try to implement them.   

Would be happy if someone could guide me to what I have to change in addition so that `.svg` icons can be used.

### CODE REVIEW

**Comment by lawmurray** [comment]
I'm just a user of Synaptic who stumbled upon this issue while wondering whether I could help with the icon too, after noticing the low res icon sticking out in a fresh Debian Trixie install. I swapped it with a generic box icon on my desktop so that it fits in. Of course, it's a very minor thing. But an SVG icon would be a nice touch I think @LLdaniel.

One thing to mention is that Synaptic *does* have a higher resolution icon in several icon themes (I'm sure the developers are aware). For example, Ubuntu users already associate Synaptic with this icon from the default [Yaru](https://github.com/ubuntu/yaru) theme:

Synaptic icon from Yaru theme, the default on Ubuntu.

For what it's worth, I also like that the above removes the anachronistic floppy disk and CD/DVD elements---or perhaps they're retro charm!

And let me just say thanks to the developers while I'm here. While I'm usually in the terminal, I much prefer Synaptic when installing packages as `apt` searches often yield many packages, and they're easier to browse through with Synaptic to find exactly what I'm looking for and check off the actions I need.

**Comment by LLdaniel** [comment]
Hi @lawmurray,
> I'm just a user of Synaptic who stumbled upon this issue while wondering whether I could help with the icon too, after noticing the low res icon sticking out in a fresh Debian Trixie install. I swapped it with a generic box icon on my desktop so that it fits in. Of course, it's a very minor thing. But an SVG icon would be a nice touch I think @LLdaniel.

I was not aware of that. Thanks for pointing this out! 

I agree, for my personal taste a kind of logo re-work would be nice due to the already mentioned anachronistic elements. But first I did not want to change the logo that drastically to keep the current "corporate" design. But if it is ok to change it completely, I could also try to propose an svg version of the yaru logo for example.

**Comment by AsciiWolf** [comment]
@mvo5 Any chance this could be merged? The 48x48 px icon is very small for today's standards and it is creating more and more problems for end-users.

In current Debian testing/sid, Synaptic is not even displayed anymore in GUI software centers like GNOME Software (and must be installed using a terminal) because of its low-res icon. See this ticket: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1091522

**Comment by AsciiWolf** [comment]
As an alternative, if a non-scalable icon is needed, a 128x128 px (or better) png icon can be created from this provided svg one.

**Comment by AsciiWolf** [comment]
> One thing to mention is that Synaptic _does_ have a higher resolution icon in several icon themes (I'm sure the developers are aware). For example, Ubuntu users already associate Synaptic with this icon from the default [Yaru](https://github.com/ubuntu/yaru) theme

The problem with that icon is in my opinion the Debian logo. Synaptic is not necessarily tied to Debian and as far as I know can be used for example on SUSE.

**Comment by AsciiWolf** [comment]
@LLdaniel This PR can be closed because #127 has already been merged.

**Comment by LLdaniel** [comment]
> @LLdaniel This PR can be closed because https://github.com/mvo5/synaptic/pull/127 has already been merged.

ah, right, halfway forgot this PR. Sure, I will close the PR in favor of the allready merged „all inclusive“ PR. ;)

**Pull request closed without merging**
